Portifolio footer
sangwa7/Portifolio pull request #4
Opened 2022-02-15 21:35 UTC by sangwa7

## Footer Section 

### -Added Footer Section with two sections:

-Footer Header 
   
-Contact Form

2022-02-15 22:11 UTC, AnselemOdims requested changes
### Hi @sangwa7, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. You can tag me using @AnselemOdims for a quicker response.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-15 22:11 UTC, AnselemOdims commented on index.html
> +        <form method="post" action="https://formspree.io/f/1">
- [ ] Please ensure that you have registered properly and gotten a valid ID on formspree. At the moment, the form is not been submitted.

2022-02-15 22:11 UTC, AnselemOdims commented on index.html
> +          <button type="submit" class="see-project-button">Get in touch</button>
- [ ] Kindly ensure that the button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template. At the moment, only hover matches the design.

![image](https://user-images.githubusercontent.com/43995830/154157902-bdd9bcd7-16f5-45c7-b38b-d0c47c0c2d48.png)

2022-02-16 08:53 UTC, elmar8287 approved these changes
Hi @sangwa7, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 08:55 UTC, merged