Web view for personal portifolio
sangwa7/Portifolio pull request #5
Opened 2022-02-18 11:13 UTC by sangwa7

## Web view for personal portfolio.

### Segments added.

- Added Navigation bar

- Added Title segment

- Added recent works segments

- Added recent projects cards 

- Added about me segment with technology, frameworks and skills 

- Added contact form

2022-02-18 11:50 UTC, micheaol requested changes
Hi @sangwa7 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-18 11:50 UTC, micheaol commented on stle.css
> +  }
Please ensure that the media queries for the Desktop breakpoint value should be `min-width` property should be in the range of `992px` - `1100px`).

```css
// Doesn't pass the requirement (too small)
@media screen and (min-width: 990px) {
/*
.
.
*/
}

// Passes the requirement (proper size)
@media screen and (min-width: 1080px) { // please note that it doesn’t have to be exactly 1080px, any value between 992 and 1100 is ok.
/*
.
.
*/
}
```

2022-02-18 11:50 UTC, micheaol commented on stle.css
> +
Please ensure that you must stick to the design as much as possible (e.g., font, colors, images, buttons, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/154674848-163ac275-97ea-42a3-92ea-89fb13e102fa.png) | ![image](https://user-images.githubusercontent.com/10332499/154674768-ca1e1907-dfc2-4bb2-af3e-e245283629fa.png)

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/154675220-adcb86d2-35ba-4dbd-b4ac-d07c9788b9c1.png) | ![image](https://user-images.githubusercontent.com/10332499/154675067-ab13a356-dc27-4ecc-bbc2-98ce613462b1.png)

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/154675794-b58c7918-ecc9-4759-b1e2-7159d5235894.png) | ![image](https://user-images.githubusercontent.com/10332499/154675451-9262959d-f8cc-4023-b5a0-464edca25563.png)

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/154677230-0f346ec6-6e70-4ad7-b931-60415a761a41.png) | ![image](https://user-images.githubusercontent.com/10332499/154677546-2a7371ee-b76e-49d6-aff5-cd390d7e8e0c.png)

Please ensure that the message on the hero `page` is on `four` lines like the design and the `social icons` are properly align-center as in the design.

2022-02-18 22:59 UTC, prolajumokeoni requested changes
Hi @sangwa7 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
- No linter errors 👍🏿 
- Good PR 👍🏿 
- GitHub flow was correctly used 👍🏿 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Check the comments under the review._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 22:59 UTC, prolajumokeoni commented on index.html
> +      <div class="socials">
Your design             |  Figma Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/69638013/154770073-35bc1208-bb3a-4d02-a217-ca70505da137.png)  | ![figma1](https://user-images.githubusercontent.com/69638013/154769006-8ed081bc-a3b6-4f66-9f43-810ad79b78b9.PNG)

- [ ] Kindly reduce the spacing between the text and icons, check the screenshot above ⬆️ 
- It would be better to make your design look like the original design as much as possible, the previous reviewer requested the text should be on four lines this was to help you understand how much width it should take, please check the reviewer's comment and make the necessary changes 👍🏿
-  [ ] Please align text to the left

2022-02-18 22:59 UTC, prolajumokeoni commented on index.html
> +          </div>
## OPTIONAL

- [ ] Well done making the requested change for the title, I noticed multi-post-stories look a little bit different kindly make your design look like the original, please check the comment about the [proper screen size](https://github.com/sangwa7/Portifolio/pull/5#discussion_r809913365) to use by the previous reviewer  👍🏿  

Figma design             |  Your Design
:-------------------------:|:-------------------------:
![figg](https://user-images.githubusercontent.com/69638013/154770970-092c2858-6818-4e09-a656-ab08fb80f473.PNG)  |  ![badddd](https://user-images.githubusercontent.com/69638013/154770985-b2c22625-a131-46ef-9d01-544e3a5f11a3.PNG)

2022-02-18 22:59 UTC, prolajumokeoni commented on index.html
> +      <div class="text-section">
## OPTIONAL

Your design             |   Figma Design
:-------------------------:|:-------------------------:
![overlap](https://user-images.githubusercontent.com/69638013/154771676-bf14384c-0b58-4e62-b0d5-36c684d91504.PNG)  | ![good overlap](https://user-images.githubusercontent.com/69638013/154771661-62d8346b-86bc-45e3-8790-157c6f1c9da6.PNG)

- [ ] It would be good if you fix this overlap, this must have been missed or not present during the previous review, the background image should be aligned to the right and not overlap the text, kindly check the screen shot 🤗

2022-02-18 23:13 UTC, prolajumokeoni commented on index.html
>            <button type="submit" class="see-project-button">Get in touch</button>
## OPTIONAL 
Your design             |  Figma Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/69638013/154773290-8f0c742b-f4f4-4edf-b345-563421dd33ac.png)  | ![touchh](https://user-images.githubusercontent.com/69638013/154773220-dfeff1b4-cfa5-4420-b534-9fd29c52b50d.PNG)

- [ ] Kindly fix the alignment of this button to look like the original design 👍🏿

2022-02-19 04:29 UTC, Kingstalux approved these changes
Hi @sangwa7 , 
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Great job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 06:51 UTC, merged